#!/usr/bin/env bash
#
# Provisions the central WireGuard server on the VPS (Debian/Ubuntu).
#
#   sudo bash setup.sh
#
# It is idempotent: run it as many times as you like. Keys are generated once
# and reused; running it again only rewrites the configuration (handy for
# adding clients).
#
# Optional variables:
#   LAN_SUBNET=192.168.1.0/24   home network the ESP32 gives access to
#   ENDPOINT=vpn.example.com      domain pointing at this VPS
#   CLIENTS="phone laptop"        clients to create (one per name)
#
# Example with another LAN:  sudo LAN_SUBNET=10.0.0.0/24 bash setup.sh
#
set -euo pipefail

LAN_SUBNET="${LAN_SUBNET:-192.168.1.0/24}"
ENDPOINT="${ENDPOINT:-vpn.example.com}"
CLIENTS="${CLIENTS:-phone laptop}"
WG_PORT="${WG_PORT:-51820}"
WG_NET="10.6.0"          # VPS .1, ESP .2, clients .10+
WG_DIR="${WG_DIR:-/etc/wireguard}"   # only changed for testing

[ "$(id -u)" = 0 ] || { echo "ERROR: run it with sudo/root." >&2; exit 1; }

# This script builds a server from scratch. If one already exists, overwriting
# it would lock out the existing peers: add the ESP32 to that config by hand.
if [ -f "$WG_DIR/wg0.conf" ] && ! grep -q "^# Generated by wgesp" "$WG_DIR/wg0.conf"; then
    echo "ERROR: $WG_DIR/wg0.conf already exists and this script did not create it." >&2
    echo "       Add the ESP32 as one more peer of your own configuration instead" >&2
    echo "       of running this (see vps/README.md). Aborting without touching" >&2
    echo "       anything." >&2
    exit 1
fi
command -v apt-get >/dev/null || { echo "ERROR: this script assumes Debian/Ubuntu." >&2; exit 1; }

echo "== 1/6 Installing packages =="
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq wireguard wireguard-tools qrencode iptables

echo "== 2/6 Generating keys (only the missing ones) =="
install -d -m 700 $WG_DIR/keys
cd $WG_DIR/keys
umask 077
gen_key() { [ -f "$1.key" ] || wg genkey | tee "$1.key" | wg pubkey > "$1.pub"; }
gen_key server
gen_key esp
for c in $CLIENTS; do gen_key "client-$c"; done

echo "== 3/6 Writing $WG_DIR/wg0.conf =="
{
    cat <<EOF
# Generated by wgesp/vps/setup.sh -- do not edit by hand, re-run the script.
[Interface]
Address = $WG_NET.1/24
ListenPort = $WG_PORT
PrivateKey = $(cat server.key)

# Let traffic flow between tunnel peers (client -> ESP32 -> home LAN).
# Needed because many VPS images ship the FORWARD chain defaulting to DROP.
PostUp   = iptables -I FORWARD -i wg0 -o wg0 -j ACCEPT
PostDown = iptables -D FORWARD -i wg0 -o wg0 -j ACCEPT

# --- ESP32-C6: gateway to the home LAN ---
[Peer]
PublicKey = $(cat esp.pub)
AllowedIPs = $WG_NET.2/32, $LAN_SUBNET
EOF
    n=10
    for c in $CLIENTS; do
        cat <<EOF

# --- Client: $c ---
[Peer]
PublicKey = $(cat "client-$c.pub")
AllowedIPs = $WG_NET.$n/32
EOF
        n=$((n + 1))
    done
} > $WG_DIR/wg0.conf
chmod 600 $WG_DIR/wg0.conf

echo "== 4/6 Enabling packet forwarding =="
sysctl -qw net.ipv4.ip_forward=1
echo 'net.ipv4.ip_forward=1' > /etc/sysctl.d/99-wgesp.conf

echo "== 5/6 Opening UDP port $WG_PORT =="
if command -v ufw >/dev/null && ufw status 2>/dev/null | grep -q "^Status: active"; then
    ufw allow "$WG_PORT/udp" >/dev/null && echo "  ufw: allowed"
elif command -v firewall-cmd >/dev/null && firewall-cmd --state >/dev/null 2>&1; then
    firewall-cmd --permanent --add-port="$WG_PORT/udp" >/dev/null
    firewall-cmd --reload >/dev/null && echo "  firewalld: allowed"
else
    echo "  no active ufw/firewalld: nothing to open in the OS"
fi

echo "== 6/6 Starting wg0 =="
systemctl enable wg-quick@wg0 >/dev/null 2>&1
if systemctl is-active --quiet wg-quick@wg0; then
    wg syncconf wg0 <(wg-quick strip wg0)   # reload without dropping the tunnel
else
    systemctl start wg-quick@wg0
fi
sleep 1
wg show wg0 || true

PUBLIC_IP="$(curl -s --max-time 5 https://api.ipify.org || echo '<your-VPS-IP>')"
OUT=$WG_DIR/wgesp-details.txt

{
echo
echo "================================================================"
echo " 1. DNS record"
echo "================================================================"
echo "   Type: A     Name: ${ENDPOINT%%.*}     Content: $PUBLIC_IP"
echo "   On Cloudflare: proxy status DNS only (GREY cloud, not orange)."
echo "   WireGuard is UDP and the Cloudflare proxy only passes HTTP."
echo
echo "================================================================"
echo " 2. Paste into sdkconfig.local of the wgesp project (dev machine)"
echo "================================================================"
echo "CONFIG_WGESP_PRIVATE_KEY=\"$(cat esp.key)\""
echo "CONFIG_WGESP_PEER_PUBLIC_KEY=\"$(cat server.pub)\""
echo "CONFIG_WGESP_ENDPOINT=\"$ENDPOINT\""
echo
echo "================================================================"
echo " 3. Clients"
echo "================================================================"
} | tee "$OUT"

n=10
for c in $CLIENTS; do
    CONF="$WG_DIR/clients/$c.conf"
    install -d -m 700 $WG_DIR/clients
    cat > "$CONF" <<EOF
[Interface]
PrivateKey = $(cat "client-$c.key")
Address = $WG_NET.$n/24

[Peer]
PublicKey = $(cat server.pub)
Endpoint = $ENDPOINT:$WG_PORT
AllowedIPs = $WG_NET.0/24, $LAN_SUBNET
PersistentKeepalive = 25
EOF
    chmod 600 "$CONF"
    { echo; echo "--- $c  ($CONF) ---"; cat "$CONF"; } | tee -a "$OUT"
    echo
    echo "QR for the WireGuard app ($c):"
    qrencode -t ansiutf8 < "$CONF"
    n=$((n + 1))
done

chmod 600 "$OUT"
echo
echo "A copy was saved in $OUT (it holds private keys: delete it when you are done)."
echo
echo "IMPORTANT: if your VPS provider has its own firewall (Hetzner/OVH/AWS/"
echo "Oracle security groups...), open UDP $WG_PORT there as well."
