#!/usr/bin/env bash
# Flashing through the Windows Python over COM3, without usbipd.
# The Hyper-V firewall of Windows 11 blocks port 3240, which 'usbipd attach'
# needs, so this is the reliable way from WSL2.
# usage: scripts/flash_win.sh [COM3]
#
# The arguments and the list of binaries are NOT written here: they come from
# build/flash_args, generated by the build. That way they cannot drift away
# from sdkconfig (flash mode, size, offsets) through copy and paste.
set -euo pipefail
cd "$(dirname "$0")/.."
COM="${1:-COM3}"
DST=/mnt/c/temp/wgesp

[ -f build/flash_args ] || { echo "ERROR: build/flash_args missing; build first." >&2; exit 1; }

# 1st line: whatever --flash_mode/--flash_freq/--flash_size apply.
# Rest: "offset path" pairs. They are copied flat into C:\temp\wgesp.
# (esptool 5 wants dashes where flash_args writes underscores)
args="$(head -1 build/flash_args | tr '_' '-')"
mkdir -p "$DST"
files=""
while read -r off path; do
    [ -n "${path:-}" ] || continue
    cp "build/$path" "$DST/"
    files="$files $off $(basename "$path")"
done < <(tail -n +2 build/flash_args)

powershell.exe -NoProfile -Command "cd C:\temp\wgesp; C:\Python314\python.exe -m esptool --chip esp32c6 --port $COM --baud 460800 --before default-reset --after hard-reset write-flash $args$files" 2>&1 | tr -d '\r' | tail -5
